[project]
name = "practice"
authors = []
description = ""
telemetry = true
requirements = []
analysis = ["check_checker"]
costs_version = 2
[contracts.practice]
path = "contracts/practice.clar"
depends_on = []
